---
-  hosts: ws
   become: true
   ignore_errors: yes
   gather_facts: yes
   vars_files:
      - vars.yml
   tasks: 
    - name: Download the zip file from GitHub
      get_url:
         url: "{{ LINK_URL }}"
         dest: "{{ DESTINATION }}"

    - name:  Delete File     
      file:
         path: "{{ DESTINATION }}"
         state: absent